on:
  release:
    types: [created]
  workflow_dispatch:

name: Build Release Docker Image
jobs:
  bls-c2w-images:
    strategy:
      matrix:
        include:
          - build: ubuntu-20.04
            os: ubuntu-20.04
            rust: stable
            runson: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            cross: false
    runs-on: ${{ matrix.runson }}
    steps:
      - uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Edit Version
        run: |
          sed -i 's/^IMAGE_TAG_VERSION=.*/IMAGE_TAG_VERSION=${{ steps.get_release.outputs.tag_name }}/g' inc.mk
      - name: Build
        run: |
          make
      - name: Login to Docker Hub
        run: |
          echo "${{secrets.GITHUB_TOKEN}}"|docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Push
        run: |
          make push
      - name: Extract
        run: |
          make extract_wasi
          tar czvf whisper.wasm.tar.gz whisper.wasm
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: whisper.wasm.tar.gz
          asset_name: whisper.wasm.tar.gz
          asset_content_type: application/gzip